In [1]:
import ogbench
import numpy as np

env = ogbench.make_env_and_datasets(
    'humanoidmaze-medium-navigate-singletask-task3-v0',
    env_only=True,
)

print('Observation space:', env.observation_space)
print('Action space:    ', env.action_space)

obs, info = env.reset(options=dict(task_id=1))
print(f'obs shape: {obs.shape}')
print(f'obs values: {obs}')
print()
print('goal shape:', info['goal'].shape)
print('goal values:', info['goal'])

# Check the underlying MuJoCo state
unwrapped = env.unwrapped
qpos = unwrapped.data.qpos.copy()
qvel = unwrapped.data.qvel.copy()
print(f'\nqpos (nq={len(qpos)}): {qpos}')
print(f'qvel (nv={len(qvel)}): {qvel}')

print('\n--- Comparing obs dims to qpos/qvel ---')
for i, v in enumerate(obs):
    print(f'  obs[{i}] = {v:.6f}')

Observation space: Box(-inf, inf, (69,), float64)
Action space:     Box(-1.0, 1.0, (21,), float32)
obs shape: (69,)
obs values: [ 8.27416939e+00  1.52631982e+01  1.64928260e-01 -7.71580517e-01
  1.55378108e-03 -4.15212764e-01 -4.05670850e-01  2.14066298e-01
 -7.31186207e-01  5.37004566e-01 -6.01515576e-01  7.59748053e-02
 -4.35913239e-01 -1.43541584e+00 -1.55266042e+00  1.56146362e-01
  4.51963716e-01 -5.17916679e-01  5.71535217e-01 -1.19563587e+00
  1.39829097e+00  1.29759344e+00 -1.40608414e+00  1.51026328e+00
 -3.96471816e-01  6.24252259e-01  2.77309147e-02  6.63812513e-01
  3.20594491e-01 -5.14989470e-01  5.57438092e-01 -2.76782514e-01
  1.98024384e-01  3.37876234e-01 -1.30293706e-01 -1.08096267e+00
  1.91770377e-01  9.79952171e-01  5.40172619e-02 -1.51128553e-02
 -3.62174992e-02 -2.35731694e-01 -6.20026839e-02 -5.43717584e-02
 -2.16842908e-01 -3.33165082e-02 -1.72457511e-01 -9.09843084e-02
  3.56996039e-02 -8.37124157e-03 -1.85054457e-02 -2.04763517e-01
  1.16704570e-01  1.7374136

In [2]:
for i in range(25):
    step = env.step(np.array([-0.1, 0.0]))
    print(step)

(array([-0.72976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.72976376, -0.59780676]), 'prev_qpos': array([-0.70976376, -0.59780676]), 'prev_qvel': array([0.06533921, 0.08793118]), 'qpos': array([-0.72976376, -0.59780676]), 'qvel': array([0., 0.]), 'success': 0.0})
(array([-0.74976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.74976376, -0.59780676]), 'prev_qpos': array([-0.72976376, -0.59780676]), 'prev_qvel': array([0., 0.]), 'qpos': array([-0.74976376, -0.59780676]), 'qvel': array([0., 0.]), 'success': 0.0})
(array([-0.76976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.76976376, -0.59780676]), 'prev_qpos': array([-0.74976376, -0.59780676]), 'prev_qvel': array([0., 0.]), 'qpos': array([-0.76976376, -0.59780676]), 'qvel': array([0., 0.]), 'success': 0.0})
(array([-0.78976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.78976376, -0.59780676]), 'prev_qpos': array([-0.76976376, -0.59780676]), 'prev_qvel': array([0., 0.]), 'qpos': array([-0.7897637

In [16]:
type(env.unwrapped.data.qvel), env.unwrapped.data.qvel.shape

(numpy.ndarray, (2,))