In [4]:
import ogbench
import numpy as np

env = ogbench.make_env_and_datasets(
    'pointmaze-medium-navigate-singletask-task1-v0',
    env_only=True,
)

print('Observation space:', env.observation_space)
print('Action space:    ', env.action_space)

obs, info = env.reset(options=dict(task_id=1))
print(f'obs shape: {obs.shape}')
print(f'obs values: {obs}')
print()
print('goal shape:', info['goal'].shape)
print('goal values:', info['goal'])

# Check the underlying MuJoCo state
unwrapped = env.unwrapped
qpos = unwrapped.data.qpos.copy()
qvel = unwrapped.data.qvel.copy()
print(f'\nqpos (nq={len(qpos)}): {qpos}')
print(f'qvel (nv={len(qvel)}): {qvel}')

print('\n--- Comparing obs dims to qpos/qvel ---')
for i, v in enumerate(obs):
    print(f'  obs[{i}] = {v:.6f}')

Observation space: Box(-inf, inf, (2,), float64)
Action space:     Box(-1.0, 1.0, (2,), float32)
obs shape: (2,)
obs values: [-0.74907606  0.33373095]

goal shape: (2,)
goal values: [20. 20.]

qpos (nq=2): [-0.74907606  0.33373095]
qvel (nv=2): [0.15450103 0.21439798]

--- Comparing obs dims to qpos/qvel ---
  obs[0] = -0.749076
  obs[1] = 0.333731


In [2]:
for i in range(25):
    step = env.step(np.array([-0.1, 0.0]))
    print(step)

(array([-0.72976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.72976376, -0.59780676]), 'prev_qpos': array([-0.70976376, -0.59780676]), 'prev_qvel': array([0.06533921, 0.08793118]), 'qpos': array([-0.72976376, -0.59780676]), 'qvel': array([0., 0.]), 'success': 0.0})
(array([-0.74976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.74976376, -0.59780676]), 'prev_qpos': array([-0.72976376, -0.59780676]), 'prev_qvel': array([0., 0.]), 'qpos': array([-0.74976376, -0.59780676]), 'qvel': array([0., 0.]), 'success': 0.0})
(array([-0.76976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.76976376, -0.59780676]), 'prev_qpos': array([-0.74976376, -0.59780676]), 'prev_qvel': array([0., 0.]), 'qpos': array([-0.76976376, -0.59780676]), 'qvel': array([0., 0.]), 'success': 0.0})
(array([-0.78976376, -0.59780676]), -1.0, False, False, {'xy': array([-0.78976376, -0.59780676]), 'prev_qpos': array([-0.76976376, -0.59780676]), 'prev_qvel': array([0., 0.]), 'qpos': array([-0.7897637

In [16]:
type(env.unwrapped.data.qvel), env.unwrapped.data.qvel.shape

(numpy.ndarray, (2,))